#include "test_extensions.h"

#include <QDebug>
#include <QTest>

#include "extensions/tables.h"

TestExtensions::TestExtensions()
{

}

TestExtensions::~TestExtensions()
{

}

void TestExtensions::initTestCase()
{

}

void TestExtensions::cleanupTestCase()
{

}

void TestExtensions::init()
{

}

void TestExtensions::cleanup()
{

}

void TestExtensions::tables()
{
    std::shared_ptr<markdown::Markdown> md = markdown::create_Markdown({
        markdown::Extension::Ptr(new markdown::TableExtension()),
    });

    QString converted = md->convert(
                "Table Tests" "\n"
                "-----------" "\n"
                "" "\n"
                "First Header  | Second Header" "\n"
                "------------- | -------------" "\n"
                "Content Cell  | Content Cell" "\n"
                "Content Cell  | Content Cell" "\n"
                "" "\n"
                "| First Header  | Second Header |" "\n"
                "| ------------- | ------------- |" "\n"
                "| Content Cell  | Content Cell  |" "\n"
                "| Content Cell  | Content Cell  |" "\n"
                "" "\n"
                "| Item      | Value |" "\n"
                "| :-------- | -----:|" "\n"
                "| Computer  | $1600 |" "\n"
                "| Phone     |   $12 |" "\n"
                "| Pipe      |    $1 |" "\n"
                "" "\n"
                "| Function name | Description                    |" "\n"
                "| ------------- | ------------------------------ |" "\n"
                "| `help()`      | Display the help window.       |" "\n"
                "| `destroy()`   | **Destroy your computer!**     |" "\n"
                "" "\n"
                "|foo|bar|baz|" "\n"
                "|:--|:-:|--:|" "\n"
                "|   | Q |   |" "\n"
                "|W  |   |  W|" "\n"
                "" "\n"
                "foo|bar|baz" "\n"
                "---|---|---" "\n"
                "   | Q |" "\n"
                " W |   | W" "\n"
                "" "\n"
                "Three spaces in front of a table:" "\n"
                "" "\n"
                "   First Header | Second Header" "\n"
                "   ------------ | -------------" "\n"
                "   Content Cell | Content Cell" "\n"
                "   Content Cell | Content Cell" "\n"
                "" "\n"
                "   | First Header | Second Header |" "\n"
                "   | ------------ | ------------- |" "\n"
                "   | Content Cell | Content Cell  |" "\n"
                "   | Content Cell | Content Cell  |" "\n"
                "" "\n"
                "Four spaces is a code block:" "\n"
                "   " "\n"
                "    First Header | Second Header" "\n"
                "    ------------ | -------------" "\n"
                "    Content Cell | Content Cell" "\n"
                "    Content Cell | Content Cell" "\n"
                "" "\n"
                "| First Header | Second Header |" "\n"
                "| ------------ | ------------- |" "\n"
                "" "\n"
                "More inline code block tests" "\n"
                "" "\n"
                "Column 1 | Column 2 | Column 3" "\n"
                "---------|----------|---------" "\n"
                "word 1   | word 2   | word 3" "\n"
                "word 1   | `word 2` | word 3" "\n"
                R"(word 1   | \`word 2 | word 3)" "\n"
                "word 1   | `word 2 | word 3" "\n"
                "word 1   | `word |2` | word 3" "\n"
                "words    |`` some | code `` | more words" "\n"
                "words    |``` some | code ``` | more words" "\n"
                "words    |```` some | code ```` | more words" "\n"
                "words    |`` some ` | ` code `` | more words" "\n"
                "words    |``` some ` | ` code ``` | more words" "\n"
                "words    |```` some ` | ` code ```` | more words" "\n"
                "" "\n"
                "A test for issue #440:" "\n"
                "" "\n"
                "foo | bar" "\n"
                "--- | ---" "\n"
                "foo | (`bar`) and `baz`.");
    QCOMPARE(converted,
             QString("<h2>Table Tests</h2>" "\n"
                     "<table>" "\n"
                     "<thead>" "\n"
                     "<tr>" "\n"
                     "<th>First Header</th>" "\n"
                     "<th>Second Header</th>" "\n"
                     "</tr>" "\n"
                     "</thead>" "\n"
                     "<tbody>" "\n"
                     "<tr>" "\n"
                     "<td>Content Cell</td>" "\n"
                     "<td>Content Cell</td>" "\n"
                     "</tr>" "\n"
                     "<tr>" "\n"
                     "<td>Content Cell</td>" "\n"
                     "<td>Content Cell</td>" "\n"
                     "</tr>" "\n"
                     "</tbody>" "\n"
                     "</table>" "\n"
                     "<table>" "\n"
                     "<thead>" "\n"
                     "<tr>" "\n"
                     "<th>First Header</th>" "\n"
                     "<th>Second Header</th>" "\n"
                     "</tr>" "\n"
                     "</thead>" "\n"
                     "<tbody>" "\n"
                     "<tr>" "\n"
                     "<td>Content Cell</td>" "\n"
                     "<td>Content Cell</td>" "\n"
                     "</tr>" "\n"
                     "<tr>" "\n"
                     "<td>Content Cell</td>" "\n"
                     "<td>Content Cell</td>" "\n"
                     "</tr>" "\n"
                     "</tbody>" "\n"
                     "</table>" "\n"
                     "<table>" "\n"
                     "<thead>" "\n"
                     "<tr>" "\n"
                     "<th>Item</th>" "\n"
                     R"(<th align="right">Value</th>)" "\n"
                     "</tr>" "\n"
                     "</thead>" "\n"
                     "<tbody>" "\n"
                     "<tr>" "\n"
                     "<td>Computer</td>" "\n"
                     R"(<td align="right">$1600</td>)" "\n"
                     "</tr>" "\n"
                     "<tr>" "\n"
                     "<td>Phone</td>" "\n"
                     R"(<td align="right">$12</td>)" "\n"
                     "</tr>" "\n"
                     "<tr>" "\n"
                     "<td>Pipe</td>" "\n"
                     R"(<td align="right">$1</td>)" "\n"
                     "</tr>" "\n"
                     "</tbody>" "\n"
                     "</table>" "\n"
                     "<table>" "\n"
                     "<thead>" "\n"
                     "<tr>" "\n"
                     "<th>Function name</th>" "\n"
                     "<th>Description</th>" "\n"
                     "</tr>" "\n"
                     "</thead>" "\n"
                     "<tbody>" "\n"
                     "<tr>" "\n"
                     "<td><code>help()</code></td>" "\n"
                     "<td>Display the help window.</td>" "\n"
                     "</tr>" "\n"
                     "<tr>" "\n"
                     "<td><code>destroy()</code></td>" "\n"
                     "<td><strong>Destroy your computer!</strong></td>" "\n"
                     "</tr>" "\n"
                     "</tbody>" "\n"
                     "</table>" "\n"
                     "<table>" "\n"
                     "<thead>" "\n"
                     "<tr>" "\n"
                     R"(<th align="left">foo</th>)" "\n"
                     R"(<th align="center">bar</th>)" "\n"
                     R"(<th align="right">baz</th>)" "\n"
                     "</tr>" "\n"
                     "</thead>" "\n"
                     "<tbody>" "\n"
                     "<tr>" "\n"
                     R"(<td align="left"></td>)" "\n"
                     R"(<td align="center">Q</td>)" "\n"
                     R"(<td align="right"></td>)" "\n"
                     "</tr>" "\n"
                     "<tr>" "\n"
                     R"(<td align="left">W</td>)" "\n"
                     R"(<td align="center"></td>)" "\n"
                     R"(<td align="right">W</td>)" "\n"
                     "</tr>" "\n"
                     "</tbody>" "\n"
                     "</table>" "\n"
                     "<table>" "\n"
                     "<thead>" "\n"
                     "<tr>" "\n"
                     "<th>foo</th>" "\n"
                     "<th>bar</th>" "\n"
                     "<th>baz</th>" "\n"
                     "</tr>" "\n"
                     "</thead>" "\n"
                     "<tbody>" "\n"
                     "<tr>" "\n"
                     "<td></td>" "\n"
                     "<td>Q</td>" "\n"
                     "<td></td>" "\n"
                     "</tr>" "\n"
                     "<tr>" "\n"
                     "<td>W</td>" "\n"
                     "<td></td>" "\n"
                     "<td>W</td>" "\n"
                     "</tr>" "\n"
                     "</tbody>" "\n"
                     "</table>" "\n"
                     "<p>Three spaces in front of a table:</p>" "\n"
                     "<table>" "\n"
                     "<thead>" "\n"
                     "<tr>" "\n"
                     "<th>First Header</th>" "\n"
                     "<th>Second Header</th>" "\n"
                     "</tr>" "\n"
                     "</thead>" "\n"
                     "<tbody>" "\n"
                     "<tr>" "\n"
                     "<td>Content Cell</td>" "\n"
                     "<td>Content Cell</td>" "\n"
                     "</tr>" "\n"
                     "<tr>" "\n"
                     "<td>Content Cell</td>" "\n"
                     "<td>Content Cell</td>" "\n"
                     "</tr>" "\n"
                     "</tbody>" "\n"
                     "</table>" "\n"
                     "<table>" "\n"
                     "<thead>" "\n"
                     "<tr>" "\n"
                     "<th>First Header</th>" "\n"
                     "<th>Second Header</th>" "\n"
                     "</tr>" "\n"
                     "</thead>" "\n"
                     "<tbody>" "\n"
                     "<tr>" "\n"
                     "<td>Content Cell</td>" "\n"
                     "<td>Content Cell</td>" "\n"
                     "</tr>" "\n"
                     "<tr>" "\n"
                     "<td>Content Cell</td>" "\n"
                     "<td>Content Cell</td>" "\n"
                     "</tr>" "\n"
                     "</tbody>" "\n"
                     "</table>" "\n"
                     "<p>Four spaces is a code block:</p>" "\n"
                     "<pre><code>First Header | Second Header" "\n"
                     "------------ | -------------" "\n"
                     "Content Cell | Content Cell" "\n"
                     "Content Cell | Content Cell" "\n"
                     "</code></pre>" "\n"
                     "<table>" "\n"
                     "<thead>" "\n"
                     "<tr>" "\n"
                     "<th>First Header</th>" "\n"
                     "<th>Second Header</th>" "\n"
                     "</tr>" "\n"
                     "</thead>" "\n"
                     "<tbody></tbody>" "\n"
                     "</table>" "\n"
                     "<p>More inline code block tests</p>" "\n"
                     "<table>" "\n"
                     "<thead>" "\n"
                     "<tr>" "\n"
                     "<th>Column 1</th>" "\n"
                     "<th>Column 2</th>" "\n"
                     "<th>Column 3</th>" "\n"
                     "</tr>" "\n"
                     "</thead>" "\n"
                     "<tbody>" "\n"
                     "<tr>" "\n"
                     "<td>word 1</td>" "\n"
                     "<td>word 2</td>" "\n"
                     "<td>word 3</td>" "\n"
                     "</tr>" "\n"
                     "<tr>" "\n"
                     "<td>word 1</td>" "\n"
                     "<td><code>word 2</code></td>" "\n"
                     "<td>word 3</td>" "\n"
                     "</tr>" "\n"
                     "<tr>" "\n"
                     "<td>word 1</td>" "\n"
                     "<td>`word 2</td>" "\n"
                     "<td>word 3</td>" "\n"
                     "</tr>" "\n"
                     "<tr>" "\n"
                     "<td>word 1</td>" "\n"
                     "<td>`word 2</td>" "\n"
                     "<td>word 3</td>" "\n"
                     "</tr>" "\n"
                     "<tr>" "\n"
                     "<td>word 1</td>" "\n"
                     "<td><code>word |2</code></td>" "\n"
                     "<td>word 3</td>" "\n"
                     "</tr>" "\n"
                     "<tr>" "\n"
                     "<td>words</td>" "\n"
                     "<td><code>some | code</code></td>" "\n"
                     "<td>more words</td>" "\n"
                     "</tr>" "\n"
                     "<tr>" "\n"
                     "<td>words</td>" "\n"
                     "<td><code>some | code</code></td>" "\n"
                     "<td>more words</td>" "\n"
                     "</tr>" "\n"
                     "<tr>" "\n"
                     "<td>words</td>" "\n"
                     "<td><code>some | code</code></td>" "\n"
                     "<td>more words</td>" "\n"
                     "</tr>" "\n"
                     "<tr>" "\n"
                     "<td>words</td>" "\n"
                     "<td><code>some ` | ` code</code></td>" "\n"
                     "<td>more words</td>" "\n"
                     "</tr>" "\n"
                     "<tr>" "\n"
                     "<td>words</td>" "\n"
                     "<td><code>some ` | ` code</code></td>" "\n"
                     "<td>more words</td>" "\n"
                     "</tr>" "\n"
                     "<tr>" "\n"
                     "<td>words</td>" "\n"
                     "<td><code>some ` | ` code</code></td>" "\n"
                     "<td>more words</td>" "\n"
                     "</tr>" "\n"
                     "</tbody>" "\n"
                     "</table>" "\n"
                     "<p>A test for issue #440:</p>" "\n"
                     "<table>" "\n"
                     "<thead>" "\n"
                     "<tr>" "\n"
                     "<th>foo</th>" "\n"
                     "<th>bar</th>" "\n"
                     "</tr>" "\n"
                     "</thead>" "\n"
                     "<tbody>" "\n"
                     "<tr>" "\n"
                     "<td>foo</td>" "\n"
                     "<td>(<code>bar</code>) and <code>baz</code>.</td>" "\n"
                     "</tr>" "\n"
                     "</tbody>" "\n"
                     "</table>"));
}

